
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author BeyzaNurCansever
 */
public class mudur_islem extends javax.swing.JFrame {

    /**
     * Creates new form mudur_islem
     */
    public mudur_islem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mudur_islem_combobox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        mudur_islem_giris = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("     MÜDÜR İŞLEM SAYFASI");

        jLabel2.setText("Lütfen Yapmak İstediğiniz İşlemi Seçiniz:");

        mudur_islem_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "İşlem Tablosunu Görüntüle", "Maaş Değiştir", "Müşteri Ekle", "Müşteri Sil", "Müşteri Bilgi Güncelle", "Müşteri Tablosu Gör", "Kur Bilgileri Güncelle", "DeadLock Analizi", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mudur_islem_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(mudur_islem_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        mudur_islem_giris.setText("GİRİŞ");
        mudur_islem_giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mudur_islem_girisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(mudur_islem_giris)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(mudur_islem_giris)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mudur_islem_girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mudur_islem_girisActionPerformed
        // TODO add your handling code here:
        String string1 = (mudur_islem_combobox.getSelectedItem()).toString();
        if (string1.equals("Müşteri Ekle")) {
            müşteri_ekle müşteri_ekle1 = new müşteri_ekle();
            müşteri_ekle1.setVisible(true);
            setVisible(false);
        }
        if(string1.equals("Müşteri Sil"))
        {
            müşteri_sil müşteri_sil1=new müşteri_sil();
            müşteri_sil1.setVisible(true);
            setVisible(false);
        }
        if(string1.equals("Müşteri Bilgi Güncelle"))
        {
            müşteri_bilgi_güncelle müşteri_bilgi_güncelle1=new müşteri_bilgi_güncelle();
            müşteri_bilgi_güncelle1.setVisible(true);
            setVisible(false);
        }
        if(string1.equals("Müşteri Tablosu Gör"))
        {
            müdür_müşteri_tablsou tablo1=new müdür_müşteri_tablsou();
            tablo1.müşteritablo();
            tablo1.setVisible(true);
            setVisible(false);
        }
        if(string1.equals("Maaş Değiştir"))
        {
            maaş_değiştir maaş=new maaş_değiştir();
            maaş.setVisible(true);
            setVisible(false);
        }
        if(string1.equals("Kur Bilgileri Güncelle"))
        {
            kur_güncelle kur_güncelle1=new kur_güncelle();
            kur_güncelle1.setVisible(true);
            setVisible(false);
        }
        if(string1.equals("İşlem Tablosunu Görüntüle"))
        {
            işlem_tablosu işlem_tablosu1=new işlem_tablosu();
            işlem_tablosu1.işlem_tablosu();
            işlem_tablosu1.setVisible(true);
            setVisible(false);
        }
        if(string1.equals("DeadLock Analizi"))
        {
            bağlantı bağlan=new bağlantı();
           int counter=0; 
           String message=" ";
           String message2=" Deadlock yoktur!";
        ArrayList<deadlock_bilgi> deadlocklar= new ArrayList<deadlock_bilgi>();
        
        deadlocklar = bağlan.deadlock_analiz();

       if(deadlocklar != null){
           
           for(deadlock_bilgi deadlock: deadlocklar){
             
             message=message+"("+deadlock.getIşlem_no1()+"-"+deadlock.getIşlemno_2()+"),";
              
             counter=deadlock.getDeadlock_no();
           }
           message=message+"\n deadlock sayısı:"+counter/2;
           JOptionPane.showMessageDialog(this, message);
       }else{        
        
            
            JOptionPane.showMessageDialog(this, message2);
       }
       
       
        
        }
    }//GEN-LAST:event_mudur_islem_girisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mudur_islem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mudur_islem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mudur_islem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mudur_islem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mudur_islem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> mudur_islem_combobox;
    private javax.swing.JButton mudur_islem_giris;
    // End of variables declaration//GEN-END:variables
}
